import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Post My Code App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-white shadow fixed w-full">
          <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
            <h1 className="text-3xl font-bold tracking-tight text-gray-900">
              PostMyCode
            </h1>
          </div>
        </header>
        <main className="container mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
          <div className="mt-20">{children}</div>
        </main>
      </body>
    </html>
  );
}
